contact_links:
  - name: ğŸ› Bug Report
    url: https://github.com/baloise/design-system/issues/new/choose
    about: Create a report to help us improve the Baloise Design System.
  - name: ğŸ’¥ Breaking Change Report
    url: https://github.com/baloise/design-system/issues/new/choose
    about: Request a breaking change an existing feature
  - name: ğŸ¨ Design Request
    url: https://github.com/baloise/design-system/issues/new/choose
    about: Suggest an idea for this project
  - name: âœ¨ Feature Report
    url: https://github.com/baloise/design-system/issues/new/choose
    about: Suggest an idea for this project
  - name: ğŸ’¬ Question
    url: https://github.com/baloise/design-system/issues/new/choose
    about: Usage question or discussion about the Baloise Design System
